### PR TITLE
Update settings ACC v1.3

### PR DESCRIPTION
**Pull request by dam09fr**
Added formationLapType parameter (not tested yet)

### CODE REVIEW

**Comment by Kugelschieber** [comment]
Hi there, I'm happy someone is working on this :) I'll look into it tomorrow and draft a new release if possible!

**Comment by dam09fr** [comment]
@Kugelschieber I'm trying to build a "Release" like yours "zip" to test on my server but I have some trouble.
Do you have a script for that ?

**Comment by Kugelschieber** [comment]
Hmm no I planned to write one but haven't done yet. You can follow the docker build and compare that to the zip files. Here are the steps:

```
# build server
go build -ldflags "-s -w" main.go

# build frontend files
cd public
npm i && npm rebuild node-sass && npm run build
```

Then copy everything to their places like in the zip. I can build one tomorrow in case you don't get it right and provide a build script.

**Comment by dam09fr** [comment]
It works ...
image

**Comment by dam09fr** [comment]
This one is also working on my server.

**Comment by Kugelschieber** [comment]
Good work, thank you very much!

**Pull request merged**
