### PR TITLE
Update 1.7.0 > fork 1.8.0

### PR DESCRIPTION
**Pull request by cestcomi**
* Minor changes to the global view
* Corrections of values for "formationLapType"
* Added parameter "simracerWeatherConditions" in event.json
* Added parameter "isFixedConditionQualification" in event.json
* Added "bop.json"
* Added "assistRules"​

IMPORTANT:
You can update the latest Release of "accweb" 1.7.0 to version 1.8.0 of this fork.
BUT, you will have to delete the servers already created in order to recreate new ones!

### CODE REVIEW

**Comment by Kugelschieber** [comment]
Can you update the readme to match this repo?

**Comment by cestcomi** [comment]
Readme updated but feel free to add/modify whatever you want.

**Comment by cestcomi** [comment]
Ok, then I should report it on the Kunos forum and ask to close my thread so that we continue the discussions on your thread ?

**Comment by Kugelschieber** [comment]
Yes.

**Pull request merged**
