### PR TITLE
Added British GT Tracks

### PR DESCRIPTION
**Pull request by fattylewis**
Got the list of names by running the 1.7 binary with an incorrect name, spits out:

```
==ERR:    'monza'
==ERR:    'brands_hatch'
==ERR:    'spa'
==ERR:    'misano'
==ERR:    'paul_ricard'
==ERR:    'zolder'
==ERR:    'silverstone'
==ERR:    'hungaroring'
==ERR:    'nurburgring'
==ERR:    'barcelona'
==ERR:    'zandvoort'
==ERR:    'monza_2019'
==ERR:    'brands_hatch_2019'
==ERR:    'spa_2019'
==ERR:    'misano_2019'
==ERR:    'paul_ricard_2019'
==ERR:    'zolder_2019'
==ERR:    'zandvoort_2019'
==ERR:    'silverstone_2019'
==ERR:    'hungaroring_2019'
==ERR:    'nurburgring_2019'
==ERR:    'barcelona_2019'
==ERR:    'kyalami_2019'
==ERR:    'mount_panorama_2019'
==ERR:    'suzuka_2019'
==ERR:    'laguna_seca_2019'
==ERR:    'oulton_park_2019'
==ERR:    'snetterton_2019'
==ERR:    'donington_2019'
==ERR:    'monza_2020'
==ERR:    'brands_hatch_2020'
==ERR:    'spa_2020'
==ERR:    'misano_2020'
==ERR:    'paul_ricard_2020'
==ERR:    'zolder_2020'
==ERR:    'zandvoort_2020'
==ERR:    'silverstone_2020'
==ERR:    'hungaroring_2020'
==ERR:    'nurburgring_2020'
==ERR:    'barcelona_2020'
==ERR:    'kyalami_2020'
==ERR:    'mount_panorama_2020'
==ERR:    'suzuka_2020'
==ERR:    'laguna_seca_2020'
==ERR:    'oulton_park_2020'
==ERR:    'snetterton_2020'
==ERR:    'donington_2020'
==ERR:    'imola_2020' 
```

### CODE REVIEW

**Comment by fattylewis** [comment]
Sorry for the PR spam....

**Comment by Kugelschieber** [comment]
No problem :D
A nice little trick there, to get the tracks.

**Comment by fattylewis** [comment]
Thanks, i intended to blindly try a bunch. I have a couple of servers already up and running. People seem to be getting overly excited and trying them constantly :D

**Comment by Kugelschieber** [comment]
Are you sure the tracks for 2020 are valid? Because they're not listed in the documentation.
[ServerAdminHandbook.pdf](https://github.com/assetto-corsa-web/accweb/files/5959646/ServerAdminHandbook.pdf)

**Comment by fattylewis** [comment]
Seems so, the server is running:

```
Starting server -= Haynet Racing =- Oulton Park (copy)
==ERR: preRaceWaitingTimeSeconds (15) has been set to 80s, 4521984 seconds are too low for public Multiplayer
allowAutoDQ is set to false, but is a public server. Will use auto DQs!
Joining during race is allowed
FileToStruct cfg/eventRules.json
maxCarSlots 28 exceeds the pit count for oulton_park_2020. Setting car slots to 28
Translated realtime interval hzToMiliseconds(18)=54

SessionManager::randomizeGreenFlagTriggers: s:0.890000 e:0.950000 r:0.916500
Track oulton_park_2020 was set and updated
Event changed
==ERR: Ignoring special event rules for public Multiplayer
==ERR: Ignoring special assist rules for public Multiplayer
SessionManager::randomizeGreenFlagTriggers: s:0.890000 e:0.950000 r:0.899035
Significant change detected, updating lobby (1|1)
maxCarSlots 28 exceeds the pit count for oulton_park_2020. Setting car slots to 28
Resetting weekend to friday night
Reset time to friday night: 0 -> 0
```

**Comment by Kugelschieber** [comment]
Interesting. I'll leave them in.

**Pull request merged**
