### PR TITLE
GT2 pack update

### PR DESCRIPTION
**Pull request by akuzia**
Added new track and car group to frontend

### CODE REVIEW

**Comment by akuzia** [comment]
Car group is not valid, server do not accept connections. strange.

**Review by Bloodsaw — COMMENTED** [review]
Checked cars and tracks.js against ServerAdminHandbook in dedicated server dir. 
Found no typos or syntax errors and the ids are correct.

For carGroups, there is no official document, but from testing in dedicated server the GT2 value is correct.

**Comment by Bloodsaw** [comment]
> Car group is not valid, server do not accept connections. strange.

Same here. Server comes up and is registered to lobby, but Car Group in UI shows as "unknown". Car selection however is correctly reduced to GT2 cargroup, cannot join either.
Since I cannot find any server in the lobby list with the GT2 filter it seems that its a bug in acc. 
Its safe to assume that GT2 is the correct value here since the server is starting.

**Review by Bloodsaw — APPROVED** [review]
See latest comments.
From my tests these changes are indeed correct and working.

**Comment by pedrofaria** [comment]
Thanks so much for your PR...

Please, update CHANGELOG.md file with version 1.24.0 then we can merge it

**Comment by pedrofaria** [comment]
[accweb_v1.24.0-rc1.zip](https://github.com/assetto-corsa-web/accweb/files/14042078/accweb_v1.24.0-rc1.zip)

for community testing

**Comment by Bloodsaw** [comment]
> [accweb_v1.24.0-rc1.zip](https://github.com/assetto-corsa-web/accweb/files/14042078/accweb_v1.24.0-rc1.zip)
> 
> for community testing

Also tested the rc1 build with track redbull ring and GT2 car class and a BoP for a GT2 car. Could connect to server.
Seems fine.

**Comment by pedrofaria** [comment]
Well I will merge and fix CHANGELOG myself

**Review by pedrofaria — APPROVED** [review]

**Pull request merged**
