### PR TITLE
added support to GT4 and carGroups

### PR DESCRIPTION
**Pull request by geppo1988**
added support to GT4 and carGroups

Can you please check ?

### CODE REVIEW

**Comment by KingWilly1** [comment]
Hi Geppo1988, 

I have build an new release and can see the new field for select an car class. After saving the server config the field Car Class is empty. Can't find where it is going wrong.

**Comment by geppo1988** [comment]
same for me on my windows it worked....but not on my server....waiting someone to help

**Comment by Kugelschieber** [comment]
I'll check.

**Comment by Kugelschieber** [comment]
Looks fine, I made some small adjustments and merged it.

**Pull request merged**
